<a href="https://colab.research.google.com/github/mv-Karthikeyan/masai/blob/main/practice_module1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
total_seats=350
remaining_seats=total_seats
total_sold=0
booked=0
rejected=0

while total_seats>0:
  Num_tickets=int(input("please enter thenumber of tickets you want between 1 as min to 15 as max:"))
  if Num_tickets<0 or Num_tickets>15:
    rejected+=1
    print(f"Booking rejected")
  else:
    valid=True
    for i in range(Num_tickets):
      age=int(input("please enter the age since it is A rated the age should be more than 12 :"))
      if age<12:
        rejected+=1
        valid=False
        print("not valid age")

      else:


        print(f" Booking successfull")
    remaining_seats-=Num_tickets
    booked+=1
  print("*"* 100)

  total_sold+=Num_tickets
  print(f"remaining tickets:{remaining_seats}")

please enter thenumber of tickets you want between 1 as min to 15 as max:3
please enter the age since it is A rated the age should be more than 12 :1
not valid age
please enter the age since it is A rated the age should be more than 12 :12
 Booking successfull
please enter the age since it is A rated the age should be more than 12 :12
 Booking successfull
****************************************************************************************************
remaining tickets:347

KeyboardInterrupt: Interrupted by user

In [ ]:
for i in range(1,11,2):
  print(i)

1
3
5
7
9

In [ ]:
for i in range(3):
  for j in range(2):
    print(i,j)

0 0
0 1
1 0
1 1
2 0
2 1

In [ ]:
for i in range(1,8):
  if i==5:
    break
  else:
    print(i)

1
2
3
4

In [ ]:
marks=[88,76,95,60,82]
def calculate(marks):

  Total=sum(marks)
  return Total

def calculte_avg(marks):
  total=calculate(marks)
  Avg=total/len(marks)
  return Avg

def get_grade(Avg):
  avg=calculte_avg(marks)
  if avg>90:
    return ("A")
  elif avg<45:
    return ("fail")

def display_report(marks):
 total= calculate(marks)
 Average=calculte_avg(marks)
 grade=get_grade(Average)
 print(total,Average,grade)


display_report(marks)

401 80.2 None

In [ ]:
cities=("nlr","kdp","vskp","Bzm","Vzm")
c1,c2,c3,c4,c5=cities
print(c1,c2,c3,c4,c5)

nlr kdp vskp Bzm Vzm

In [ ]:
#sets

passed_python={"kar","Ram","jaya","MRK","Man"}
passed_sql={"kar","Ma","Sures","Surek","Amamma"}
union=passed_python|passed_sql
intersection=passed_python&passed_sql
difference=passed_python-passed_sql

print(union,intersection,difference)

{'jaya', 'Ma', 'kar', 'Sures', 'Surek', 'Amamma', 'Man', 'Ram', 'MRK'} {'kar'} {'jaya', 'Man', 'MRK', 'Ram'}

In [ ]:
ascii=[65,66,67,68,69]
for i in ascii:
  print(f"{i}:{chr(i)}")

65:A
66:B
67:C
68:D
69:E

In [ ]:
import subprocess
result=subprocess.run("whoami",shell=True,capture_output=True,text=True)
print(result.stdout)

root

In [ ]:
import json
student={
    'name':"karthik",
    'age':25,
    'passed':True,
    'marks' : [55,66,77],
    'address':{
        'city':"nellore",
        'pincode':524004
    }
}
json_str=json.dumps(student,indent=5)
print(json_str)
jsonload=json.loads(json_str)
print(jsonload)

{
     "name": "karthik",
     "age": 25,
     "passed": true,
     "marks": [
          55,
          66,
          77
     ],
     "address": {
          "city": "nellore",
          "pincode": 524004
     }
}
{'name': 'karthik', 'age': 25, 'passed': True, 'marks': [55, 66, 77], 'address': {'city': 'nellore', 'pincode': 524004}}

In [ ]:
products=[
    {"name":"mobile","price":55555,"segment":"electronic"},
    {"name":"car","price":555555,"segment":"automobile"}
]
data=json.dumps(products,indent=5)
print(data)

[
     {
          "name": "mobile",
          "price": 55555,
          "segment": "electronic"
     },
     {
          "name": "car",
          "price": 555555,
          "segment": "automobile"
     }
]

In [ ]:
#file handling

with open("warehousedata.txt","w") as file:
  file.write('120\n')
  file.write('130\n')
  file.write('140\n')
  file.write('150\n')
  file.write('160\n')
with open('warehousedata.txt','r') as file:
  lines=file.readlines()
values=[line.strip() for line in lines]
for v in values:
  print(v)

120
130
140
150
160

In [ ]:
import numpy as np
arr=np.array(values,dtype=int)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[120 130 140 150 160]
int64
(5,)
5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

In [ ]:
b=np.arange(1,100)
print(b)
print(b.dtype)
print(b.shape)
sum=np.sum(b)
max=np.max(b)
Avg=np.mean(b)

minimum=np.min(b)
print(sum)
print(max)
print(Avg)

print(minimum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
int64
(99,)
4950
99
50.0
1

In [ ]:
#numpy imp:

import numpy as np

np.random.seed(42) # for repeatability

name=np.random.choice(["karthik","ramana","jaya","ramakrishan","manasa"],size=10)
ages=np.random.randint(25,55,size=10)
maths=np.random.randint(55,99,size=10)
physics=np.random.randint(25,99,size=10)
english=np.random.randint(35,99,size=10)

#marks=np.array([maths,physics,english])
marks=np.array([maths,physics,english]).T
# print(marks)
# print(marks.dtype,marks.shape)
print(marks)
print(marks.dtype,marks.shape)
reshape=marks.reshape(2,5,3)
print("reshape:")
print(reshape)
sliced=marks[:5,:2]
print(sliced)

#write in file

with open("student_record.txt","w") as file:
  file.write(f"Name | Age | Maths | Physics  | English \n")
  for i in range(10):
    file.write(f"{name[i]} | {ages[i]} | {maths[i]} | {physics[i]}  | {english[i]}\n")
  print("successfully added")

with open("student_record.txt","r") as file:
    lines=file.readlines()
print("readed")


for line in lines:
    print(line.strip())

[[92 84 71]
 [56 39 85]
 [75 86 41]
 [87 86 55]
 [66 71 43]
 [76 86 73]
 [98 75 52]
 [79 79 38]
 [81 88 59]
 [96 27 94]]
int64 (10, 3)
reshape:
[[[92 84 71]
  [56 39 85]
  [75 86 41]
  [87 86 55]
  [66 71 43]]

 [[76 86 73]
  [98 75 52]
  [79 79 38]
  [81 88 59]
  [96 27 94]]]
[[92 84]
 [56 39]
 [75 86]
 [87 86]
 [66 71]]
successfully added
readed
Name | Age | Maths | Physics  | English
ramakrishan | 28 | 92 | 84  | 71
manasa | 32 | 56 | 39  | 85
jaya | 48 | 75 | 86  | 41
manasa | 27 | 87 | 86  | 55
manasa | 46 | 66 | 71  | 43
ramana | 45 | 76 | 86  | 73
jaya | 26 | 98 | 75  | 52
jaya | 48 | 79 | 79  | 38
jaya | 36 | 81 | 88  | 59
manasa | 54 | 96 | 27  | 94

In [ ]:
#pandas

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np



df=sns.load_dataset("titanic")
df
# df.shape
# df.columns
# df.dtypes
# df.describe()
# df.info()
# df.isnull().sum().sum()
# df.fillna(df.mode().iloc[0],inplace=True)
# df
df.columns

renamed=df.rename(columns={"pclass":"passenger","sex":"gender"})
print(renamed)

df.iloc[:3,:6]

     survived  passenger  gender   age  sibsp  parch     fare embarked  \
0           0          3    male  22.0      1      0   7.2500        S
1           1          1  female  38.0      1      0  71.2833        C
2           1          3  female  26.0      0      0   7.9250        S
3           1          1  female  35.0      1      0  53.1000        S
4           0          3    male  35.0      0      0   8.0500        S
..        ...        ...     ...   ...    ...    ...      ...      ...
886         0          2    male  27.0      0      0  13.0000        S
887         1          1  female  19.0      0      0  30.0000        S
888         0          3  female   NaN      1      2  23.4500        S
889         1          1    male  26.0      0      0  30.0000        C
890         0          3    male  32.0      0      0   7.7500        Q

      class    who  adult_male deck  embark_town alive  alone
0     Third    man        True  NaN  Southampton    no  False
1     First  woman       False    C    Cherbourg   yes  False
2     Third  woman       False  NaN  Southampton   yes   True
3     First  woman       False    C  Southampton   yes  False
4     Third    man        True  NaN  Southampton    no   True
..      ...    ...         ...  ...          ...   ...    ...
886  Second    man        True  NaN  Southampton    no   True
887   First  woman       False    B  Southampton   yes   True
888   Third  woman       False  NaN  Southampton    no  False
889   First    man        True    C    Cherbourg   yes   True
890   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

   survived  pclass     sex   age  sibsp  parch
0         0       3    male  22.0      1      0
1         1       1  female  38.0      1      0
2         1       3  female  26.0      0      0

In [ ]:
import seaborn as sns
df=sns.load_dataset("titanic")

In [ ]:
Titanic=sns.load_dataset("titanic")
filter=Titanic[
    (Titanic["sex"]=="female") & (Titanic["pclass"].isin([1,2]))
]

filter.loc[:,"age"]=filter["age"].fillna(30)
sort=filter.sort_values(by="fare",ascending=False).reset_index()
filter['fare_group']="high"
filter.to_csv("female.csv")

/tmp/ipykernel_1710/3296596404.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter['fare_group']="high"

In [ ]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
titanic=sns.load_dataset("titanic")

In [ ]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
summary=(
    titanic.groupby(["pclass","sex"]).agg(
        total_pass=("survived",'count'),
        survivors=("survived","sum"),
        sur_rate=("survived","mean"),
        avg_age=("age","mean"),
        max_fare=("fare","max")
    ).reset_index()
)
summary

   pclass     sex  total_pass  survivors  sur_rate    avg_age  max_fare
0       1  female          94         91  0.968085  34.611765  512.3292
1       1    male         122         45  0.368852  41.281386  512.3292
2       2  female          76         70  0.921053  28.722973   65.0000
3       2    male         108         17  0.157407  30.740707   73.5000
4       3  female         144         72  0.500000  21.750000   69.5500
5       3    male         347         47  0.135447  26.507589   69.5500